spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    port: 587
    username: 980742324@qq.com
    password: mtdomlplzqkzbbce
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  datasource:
    schema: classpath:datasource/schema.sql
    data: classpath:datasource/data.sql
    separator: $$
    continue-on-error: true
server:
  servlet:
    context-path: /api
  port: 521
  ssl:
    key-store: bobo.p12
    key-alias: bobossl
    key-store-password: songyanan521
# pageHelper配置
pagehelper:
  #  dialect: mysql 高版本可以自动识别，不需要配置方言，否则会报错
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis:
  mapper-locations:
    - classpath:mapper/blog/*.xml
    - classpath:mapper/global/*.xml
mail:
  fromMail:
    addr: 980742324@qq.com