spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    port: 587
    username: 980742324@qq.com
    password: mtdomlplzqkzbbce
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  datasource:
    schema: classpath:datasource/schema.sql
    data: classpath:datasource/data.sql
    separator: $$
    continue-on-error: true
  redis:
    keyPrefix:
      all: "com.aqzscn.web:"
      wxfunc: "weixin.modules:"
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #默认-1 最大连接阻塞等待时间
        max-idle: 8 #最大空闲连接 默认8
        min-idle: 0 #最小空闲连接
server:
  servlet:
    context-path: /api
#  ssl:
#    key-store: bobo.p12
#    key-alias: bobossl
#    key-store-password: songyanan521
# pageHelper配置
pagehelper:
  #  dialect: mysql 高版本可以自动识别，不需要配置方言，否则会报错
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis:
  mapper-locations:
    - classpath:mapper/blog/*.xml
    - classpath:mapper/global/*.xml
mail:
  fromMail:
    addr: 980742324@qq.com
myoptions:
  weixin:
    hitokoto:
      url: