spring:
  profiles:
    active: dev
  mail:
    # 邮箱配置，我这里配置的是QQ邮箱
    host: smtp.qq.com
    port: 587
    # 邮箱账号
    username: xxx@qq.com
    # 授权码，不是密码。。
    password: inputYourCode
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  datasource:
    schema: classpath:datasource/schema.sql
    data: classpath:datasource/data.sql
    separator: $$
    continue-on-error: true
  redis:
    keyPrefix:
      all: "com.aqzscn.web:"
      wxfunc: "weixin.modules:"
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #默认-1 最大连接阻塞等待时间
        max-idle: 8 #最大空闲连接 默认8
        min-idle: 0 #最小空闲连接
server:
  servlet:
    context-path: /api
#  ssl:
#    key-store: bobo.p12
#    key-alias: bobossl
#    key-store-password: songyanan521
# pageHelper配置
pagehelper:
  #  dialect: mysql 高版本可以自动识别，不需要配置方言，否则会报错
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis:
  mapper-locations:
    - classpath:mapper/blog/*.xml
    - classpath:mapper/global/*.xml
mail:
  # 配置邮箱发送者的信息
  fromMail:
    addr: xxx@qq.com
myoptions:
  weixin:
    hitokoto:
      url:
  global:
    # 注册时是否验证用户邮箱
    user-email-validate: true